<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Video;
use Input, DB, Auth, Redirect, Validator, View;
use App\User;
use App\Ads;
use App\Settings;
use App\Services\PricesClass;
class VideoController extends Controller
{
    //
	private function UploadFile($sourcePath, $dropboxPath){ 
		$token = Settings::where('key', '=', 'dropboxTokenKey')->first();
		$accesstoken  = $token->value;
		$abc = new PricesClass();
		$path = $abc->UploadFile($accesstoken, $dropboxPath, $sourcePath);
		unlink($sourcePath);
		$url = $abc->getLink($accesstoken,$path);
		return $url;
	}
	
	
	private function getsharelink($dropboxPath){
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
			$ch = curl_init();
			curl_setopt($ch, CURLOPT_URL, "https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings");
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"path\": \"". $dropboxPath  ."\",\"settings\": {\"requested_visibility\": \"public\"}}");
			curl_setopt($ch, CURLOPT_POST, 1);

			$headers = array();
			$headers[] = "Authorization: Bearer qt3CnAk9F1AAAAAAAAAAaWYDEsUXfHMTMhSzcDgzqbouMWiz6hlGpLqFB1MvWafF";
			$headers[] = "Content-Type: application/json";
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

			$response = curl_exec($ch);
			if (curl_errno($ch)) {
				echo 'Error:' . curl_error($ch);
			}
			curl_close ($ch);
			$result =  json_decode($response);
			
			$url  = substr($result->url , 0 ,  strlen($result->url) - 1) . '1';
			return $url;
	}
	
	private function Uploadimagetodropbox($dropboxPath, $sourcePath){
			$ch = curl_init();
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
			curl_setopt($ch, CURLOPT_POST, true);

			$token = "qt3CnAk9F1AAAAAAAAAAaWYDEsUXfHMTMhSzcDgzqbouMWiz6hlGpLqFB1MvWafF";
			$host = "https://content.dropboxapi.com/2/files/upload";

			//set headers
			$headers = array('Authorization: Bearer '.$token,
			 'Content-Type: application/octet-stream',
			 'Dropbox-API-Arg: {"path":"'. $dropboxPath  .'","mode":"add"}',
			);
		 
			$f = fopen($sourcePath, "rb");
			
			curl_setopt($ch, CURLOPT_URL, $host);
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

			// What should the POST data look like? Using the file handle? That doesn't work.
			curl_setopt($ch, CURLOPT_POSTFIELDS, $dropboxPath);
			curl_setopt($ch, CURLOPT_POSTFIELDS, fread($f, filesize($sourcePath)));
			 
			fclose($f);
			$response = curl_exec($ch);
			curl_close($ch);
			
			$result =  json_decode($response);
			return $result->path_display;
	}
	
	
	
	
	public function uploadvideo(Request $request){
		//save the data 
		$validator = Validator::make($request->all(),
		  [	'title_upload_video' => 'required',
			'video_url' => 'required',
			'videotype' => 'required',
			'video_content' => 'required',
			'uploadsong_img_video'    => 'required|image|mimes:jpeg,bmp,png'
			]
		)->validate();
		
		$uploadsong_img_video=$request->uploadsong_img_video;
		
		if($uploadsong_img_video){
			if(Auth::user()->status == 1){
				
				$video = new Video;
				$video->title  = $_POST['title_upload_video'];
				$video->URL = $_POST['video_url'];
				$video->description  = $_POST['video_content'];
				$video->artise_id = Auth::user()->id;
				
				$video->type =  $_POST['videotype'];
				
				
				$imageName=$uploadsong_img_video->hashName();
				$uploadsong_img_video->store('images');
				$sourcePath     = storage_path() . "/app/images/" . $imageName;
				$dropboxPath    = '/images/' . $imageName;
				
				
				$imagepath =  $this->Uploadimagetodropbox($dropboxPath, $sourcePath);
				$video->image   = $this->getsharelink($imagepath);
				 
				 
				if(Auth::user()->approved == 1) $video->status = 1;
				
				// check auto
				$token = Settings::where('key', '=', 'autoapprove')->first();
				if($token->value){
					$auto_enable = Video::where('artise_id', Auth::user()->id)
										->where('status', 1)
										->count();
					if($auto_enable)
						$video->status = 1;
				}
				
				$ret = $video->save();
			}
		}
		return Redirect::back()->with(['msg', 'The Message']);
	}
	
	public function browse_admin_video(){
		$videos = Video::orderBy('created_at', 'DESC')->paginate(10);
		$permission_array  = app('App\Http\Controllers\HomeController')->getPermssion();
		return view('adminvideo', compact('videos','permission_array'));
	}
	
	
	public function publishVideo(){
		// update
		$msg = "This is a simple message.";
		
		$user_id = $_POST['user_id'];
		$id = $_POST['id'];
		$act = $_POST['act'];
		
		$video = Video::find($id);
		$video->status  = $act;
		$ret = $video->save();
		if($ret) {
			$status = 1;
			$msg = "Setting success";
		}
		else{
			$status = 0; 
			$msg = "Setting failed";
		}
		
		// send email
		if($act == '1'){
			$user = User::find($user_id);
			$email  = $user->email;
			
			
			
			$message = "Hello ". $user->name."! <br/> Your  Video has been approved.   Share the link below on your social media pages to help promote it. We also have a premium promotion service where we can promote your songs,lyrics & Youtube videos to 1000s of Facebook, Twitter and Youtubers.
				<br/>
				<br/>
				Interested ? Send us an email : promo@africaworships.com
		        Link to share : <a href = 'http://africaworships.com/video-detail/". $video->title. "/". $video->id ."'>link here </a>
				<br/>
				Thanks<br/>
				Africa Worships Team
			";
			
			
			$subject = "worship @". $user->name;
			$headers  = "From: worship \r\n";
			$headers .= "Reply-To:\r\n";
			
			$headers .= "MIME-Version: 1.0\r\n";
			$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
			mail($email, $subject, $message, $headers);
		}
		
		return response()->json(array('msg'=> $msg, 'status'=> $status), 200);
	}
	
	
	public function deletevideo($id){
		$video = Video::find($id);
		if(count($video))
			$video->delete();
		$video = Video::all();
		return redirect('adminvideo')->with(compact('video'));
	}
	
	public function browse(){
		if(isset($_GET['sort'])){
			
			$videos =DB::table('video')->select('video.*', 'users.name')->leftJoin('users', 'users.id', '=', 'video.artise_id')->whereRaw("title like '".$_GET['sort']."%' or title like '".strtoupper($_GET['sort'])."%'")->orderBy('video.updated_at', 'desc')->get();
		}
		else
			$videos =DB::table('video')->select('video.*', 'users.name')->leftJoin('users', 'users.id', '=', 'video.artise_id')->whereRaw(" video.status = '1' ")->orderBy('video.updated_at', 'desc')->get();
		
		$ads = Ads::whereRaw('menu = "4" and status = "1"')->get();
		
		return view('video', array('videos'=> $videos, 'likesongs'=>app('App\Http\Controllers\SongsController')->getfavoritesongs(), 'playlists' => app('App\Http\Controllers\SongsController')->getplaylistsongs(), 'ads' => $ads));
	}
	
	public function getVideo($name, $id){	
		$video =DB::table('video')->select('video.*', 'users.name')->leftJoin('users', 'users.id', '=', 'video.artise_id')->whereRaw(" video.id = '$id' ")->orderBy('video.updated_at', 'desc')->first();
				
		return view('videodetail', array('video' => $video, 'likesongs'=>app('App\Http\Controllers\SongsController')->getfavoritesongs(),  'playlists' => app('App\Http\Controllers\SongsController')->getplaylistsongs()));
	}
	
}
